### ISSUE TITLE
Editable title for each Save

### ISSUE THREAD

**Issue by dhruvitahrishi** [allen505/save-for-later-firefox#4]

**Comment by allen505** [comment]
Thank you for your interest @dhruvitahrishi ! This is surely a useful feature to have.
### Implementation Details
- I think we'll be able to make this possible by using [contenteditable](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable) attribute on the button text or by changing it from a `button` to `a` link. 
- The title of each Save will a Editable text which by default is the text currently present (date,time and number of tabs), but if the user wants he can edit it by clicking on it. After clicking on it, it should be editable and user can type in his desired text and hit enter, which should save the text.
- Since the text will be editable, we need to have a seperate button which will launch all the tabs in a new window with a logo similar to [this](https://thenounproject.com/search/?q=new+tab&i=1167424).

Let me know if you are interested in working on this feature.

**Comment by AB047** [comment]
I think this is going to be an easy fix, I can do this.

**Comment by allen505** [comment]
Definitely @AB047 you can give a try. Please have a look at [my message above ](https://github.com/allen505/save-for-later/issues/4#issuecomment-647880359)implementation details. For any further clarifications please drop your questions on this thread

**Comment by emecas** [comment]
**Experimenting with editable titles**

![image](https://user-images.githubusercontent.com/849502/93793259-96e6d380-fc04-11ea-98a9-e386687c7ff1.png)


**Experimenting with available area keeping intact title information**

![image](https://user-images.githubusercontent.com/849502/93795867-03af9d00-fc08-11ea-9874-8e799268209f.png)

**Comment by allen505** [comment]
This is amazing work @emecas . The first image is exactly what I had in mind as mentioned in [this comment](https://github.com/allen505/save-for-later/issues/7#issuecomment-696495930). Since the text will be editable, we need to have a seperate button which will launch all the tabs in a new window with a logo similar to [this](https://thenounproject.com/search/?q=new+tab&i=1167424). We have to shift all the icons to the right side however as to me it looks a bit odd to have unevenly distributed icons. I will repeat the implementation details of the Editable text in the begining of this thread too for reference. 


Please do let me know if you are interested to work on this. One thing I forgot in the developement setup is to create a new `branch` to keep your feature implementation seperate from the `master` branch code. To do this enter:
`git checkout -b <new-branch-name>`
in a terminal.

**Comment by emecas** [comment]
Thanks @allen505 

Following your indications and priorities, I'm working on this issue first and almost done.

**Progresses:**

 - [x] 1) Editing the title and controlling its length > 0 and max based on the available area to avoid the buttons move or miss-align.
 
 - [x] 2) Added a new launch button with the image suggested and relocated the logic to launch all the tabs clicking it.

 - [x] 3) Moved the icons to the right

~~**To do**~~

~~For now~~ I was having issues with 2 things:

 - [x] 4) Once the edition of the title is done, then while attempting replacing/updating only the title's value in the local storage object is still failing. I have tried different approaches, it's not refreshed properly, So I'm still working on it. Also, it seems like you can only replace the full object in  the storage.

 - [x] 5) Ordering the icons at the right in specific desired order, I have 3 stiles with `float: right;`  but I am not sure what is the order followed by the browser to locate the buttons (if it is based on the order you added them, or alphabetic order, or what is the criteria). these get located like:  delete, launch and expand , but i would like to see: launch, expand, delete. I think it needs an extra DIV in order to put the buttons there in the desired order.

**Final Result:**

![image](https://user-images.githubusercontent.com/849502/94097070-babc3c00-fdf3-11ea-8a13-6f21d6d51073.png)

**Comment by allen505** [comment]
Adding some changes which are to be addressed:

- [x] To make the changes less jarring for the end users, I'm looking to make an edit button which enables the editableContent and a click on the Title to open the Save, as it was previously. This also gives more click area for most used feature which would be to repoen the Saves
- [x] Space is not accepted in Chrome
- [ ] Title String Validations Required:
  - [ ] Empty String is being accepted
  - [ ] Very long Titles are accepted

**Comment by emecas** [comment]
> Adding some changes which are to be addressed:
> 
>     * To make the changes less jarring for the end users, I'm looking to make an edit button which enables the editableContent and a click on the Title to open the Save, as it was previously. This also gives more click area for most used feature which would be to repoen the Saves
> 
>     * Space is not accepted in Chrome
> 
>     * Title String Validations Required:
>       
>       * Empty String is being accepted
>       * Very long Titles are accepted

hi @allen505, are you working on this currently? I could give this another try, I just need to know where we are

**Comment by allen505** [comment]
Hey @emecas , I had started on the changes but couldn't find the time to complete it. You can pick it up some parts of this if you are available

**Comment by allen505** [comment]
Closing this issue
